added math module with ceiling method and a test case
R055A/voc pull request #1
Opened 2020-09-14 09:58 UTC by ponterik

2020-09-14 13:11 UTC, R055A requested changes
TranspileTestCase should be used in the test.

2020-09-15 07:55 UTC, merryaiiit approved these changes
The module looks good.

2020-09-15 07:56 UTC, R055A approved these changes

2020-09-15 07:58 UTC, nguyenluc99 approved these changes

2020-09-15 07:58 UTC, merged