Tests for and fixes to all existing Date.java functionlity
R055A/voc pull request #50
Opened 2020-09-27 18:05 UTC by R055A

2020-09-29 09:48 UTC, DavidOstlund commented
## Review
The code looks good and as you mentioned the code coverage is really high at 100% class coverage, 94% method coverage and 97% line coverage. We have some comments about how to make the code more readable. 

### Date.java
There are some long one liners on line 384 and line 344+345.
We believe that breaking them up over several assignments would increase readability.

Some comments explaining the if statement starting on line 368 and ending on line 374 would help with understanding what's going on.
It was a bit hard to see what the non variable numbers represented by just reading the code.

Out of curiosity we were also wondering in what order you did your tests.
Did you first create them and then do coverage, or the other way around?
We have not looked at every test in detail but we were wondering if might be possible to get a similar amount of coverage with less tests.

Anyhow, really great job.
Well done!

2020-09-29 10:36 UTC, R055A commented
> 
> ## Review
> 
> The code looks good and as you mentioned the code coverage is really high at 100% class coverage, 94% method coverage and 97% line coverage. We have some comments about how to make the code more readable.
> ### Date.java
> 
> There are some long one liners on line 384 and line 344+345.
> We believe that breaking them up over several assignments would increase readability.
> 
> Some comments explaining the if statement starting on line 368 and ending on line 374 would help with understanding what's going on.
> It was a bit hard to see what the non variable numbers represented by just reading the code.
> 
> Out of curiosity we were also wondering in what order you did your tests.
> Did you first create them and then do coverage, or the other way around?
> We have not looked at every test in detail but we were wondering if might be possible to get a similar amount of coverage with less tests.
> 
> Anyhow, really great job.
> Well done!

Thank you!

The tests are created first. Then the methods are fixed so that they pass the testing for them. The coverage is a measure of how well the methods are tested, if all the different possible implemented outcomes are considered in the testing, and is only relevant when they are tested. Thus, the tests must come first. The methods being tested require having all tested functionalities implemented to pass all tests. If all tests are passing then the methods have all this functionality and, unless the methods have additional irrelevant implementations, the coverage should always be high. If any tests are removed, then not all functionality implemented to pass these tests will be covered by the testing and the coverage report will show this with lower percentages. 

When you run code coverage it is possible to also check for branch coverage. This can be done in IntelliJ by selecting tracing in the code coverage options. The branch coverage when last run was above 80%, but you should check for yourself to be sure.

As for lines 344 and 345, the attributes for each of year, month and day from the LocalDate.now() instance are being converted to org.python.types.Int type in an Object[] array so they can be passed as args in a new Date() instance being returned in the next line. This will be broken up to help with readability as requested very soon.

As for line 384, this is a solution to the weekday() method bug. First, this.weekdays is a HashMap that maps each weekday String return by the java LocalDate().getDayOfWeek() method to its corresponding weekday number returned by the Python datetime.date().weekday() method. The HashMap is initialized as a global, and can be found declared at line #50 and initialized and set from lines #126 to #133. To get the weekday String, it is required to use the LocalDate.parse() method. To get a string to enter as an argument to this method, either the datetime.date().str() method is required or, otherwise, the inbuilt __repr__() method, which is what is being given as the argument to LocalDate.parse(). The __repr__() method can be found at lines #297 to #311. This can also be broken up to help with readability as requested, which will be done very soon.

I hope that that answered your questions adequately. 

As for lines 368 to 374, this will require being answered by @nguyenluc99, the collaborator responsible for the bug fix.

2020-09-29 12:29 UTC, nguyenluc99 requested changes
Just a small change in checking a leap year.
Leap year is a year which is divided by 4, not divided by 100; or divided by 400.

2020-09-29 12:36 UTC, R055A commented on python/common/org/python/stdlib/datetime/Date.java
> +            if (this.year.value % 4 == 0) {
These are not the lines of code being referred to by @DavidOstlund

2020-09-29 12:46 UTC, R055A commented on python/common/org/python/stdlib/datetime/Date.java
> +        return new org.python.types.Str(weekdayStr + " " + monthStr + " " + dayStr + " 00:00:00 " + yearStr);
@DavidOstlund wants to understand what the code does between lines 368 and 374. He is requesting some line comments.

2020-09-29 12:50 UTC, DavidOstlund commented
> > ## Review
> > The code looks good and as you mentioned the code coverage is really high at 100% class coverage, 94% method coverage and 97% line coverage. We have some comments about how to make the code more readable.
> > ### Date.java
> > There are some long one liners on line 384 and line 344+345.
> > We believe that breaking them up over several assignments would increase readability.
> > Some comments explaining the if statement starting on line 368 and ending on line 374 would help with understanding what's going on.
> > It was a bit hard to see what the non variable numbers represented by just reading the code.
> > Out of curiosity we were also wondering in what order you did your tests.
> > Did you first create them and then do coverage, or the other way around?
> > We have not looked at every test in detail but we were wondering if might be possible to get a similar amount of coverage with less tests.
> > Anyhow, really great job.
> > Well done!
> 
> Thank you!
> 
> The tests are created first. Then the methods are fixed so that they pass the testing for them. The coverage is a measure of how well the methods are tested, if all the different possible implemented outcomes are considered in the testing, and is only relevant when they are tested. Thus, the tests must come first. The methods being tested require having all tested functionalities implemented to pass all tests. If all tests are passing then the methods have all this functionality and, unless the methods have additional irrelevant implementations, the coverage should always be high. If any tests are removed, then not all functionality implemented to pass these tests will be covered by the testing and the coverage report will show this with lower percentages.
> 
> When you run code coverage it is possible to also check for branch coverage. This can be done in IntelliJ by selecting tracing in the code coverage options. The branch coverage when last run was above 80%, but you should check for yourself to be sure.
> 
> As for lines 344 and 345, the attributes for each of year, month and day from the LocalDate.now() instance are being converted to org.python.types.Int type in an Object[] array so they can be passed as args in a new Date() instance being returned in the next line. This will be broken up to help with readability as requested very soon.
> 
> As for line 384, this is a solution to the weekday() method bug. First, this.weekdays is a HashMap that maps each weekday String returned by the java LocalDate().getDayOfWeek() method to its corresponding weekday number returned by the Python datetime.date().weekday() method. The HashMap is initialized as a global, and can be found declared at line 50 and initialized and set from lines 126 to 133. To get the weekday String, it is required to use the LocalDate.parse() method. To get a string to enter as an argument to this method, either the datetime.date().__str__() method is required or, otherwise, the inbuilt __repr__() method, which is what is being given as the argument to LocalDate.parse(). The __repr__() method can be found at lines 297 to 311. Line 384 can also be broken up to help with readability as requested, which will be done very soon.
> 
> I hope that that answered your questions adequately.
> 
> As for lines 368 to 374, this will require being answered by @nguyenluc99, the contributor responsible for the bug fix.

2020-09-29 12:52 UTC, DavidOstlund commented
> > ## Review
> > The code looks good and as you mentioned the code coverage is really high at 100% class coverage, 94% method coverage and 97% line coverage. We have some comments about how to make the code more readable.
> > ### Date.java
> > There are some long one liners on line 384 and line 344+345.
> > We believe that breaking them up over several assignments would increase readability.
> > Some comments explaining the if statement starting on line 368 and ending on line 374 would help with understanding what's going on.
> > It was a bit hard to see what the non variable numbers represented by just reading the code.
> > Out of curiosity we were also wondering in what order you did your tests.
> > Did you first create them and then do coverage, or the other way around?
> > We have not looked at every test in detail but we were wondering if might be possible to get a similar amount of coverage with less tests.
> > Anyhow, really great job.
> > Well done!
> 
> Thank you!
> 
> The tests are created first. Then the methods are fixed so that they pass the testing for them. The coverage is a measure of how well the methods are tested, if all the different possible implemented outcomes are considered in the testing, and is only relevant when they are tested. Thus, the tests must come first. The methods being tested require having all tested functionalities implemented to pass all tests. If all tests are passing then the methods have all this functionality and, unless the methods have additional irrelevant implementations, the coverage should always be high. If any tests are removed, then not all functionality implemented to pass these tests will be covered by the testing and the coverage report will show this with lower percentages.
> 
> When you run code coverage it is possible to also check for branch coverage. This can be done in IntelliJ by selecting tracing in the code coverage options. The branch coverage when last run was above 80%, but you should check for yourself to be sure.
> 
> As for lines 344 and 345, the attributes for each of year, month and day from the LocalDate.now() instance are being converted to org.python.types.Int type in an Object[] array so they can be passed as args in a new Date() instance being returned in the next line. This will be broken up to help with readability as requested very soon.
> 
> As for line 384, this is a solution to the weekday() method bug. First, this.weekdays is a HashMap that maps each weekday String returned by the java LocalDate().getDayOfWeek() method to its corresponding weekday number returned by the Python datetime.date().weekday() method. The HashMap is initialized as a global, and can be found declared at line 50 and initialized and set from lines 126 to 133. To get the weekday String, it is required to use the LocalDate.parse() method. To get a string to enter as an argument to this method, either the datetime.date().__str__() method is required or, otherwise, the inbuilt __repr__() method, which is what is being given as the argument to LocalDate.parse(). The __repr__() method can be found at lines 297 to 311. Line 384 can also be broken up to help with readability as requested, which will be done very soon.
> 
> I hope that that answered your questions adequately.
> 
> As for lines 368 to 374, this will require being answered by @nguyenluc99, the contributor responsible for the bug fix.

Thank you for the answers.
Now I understand what's going on :)

2020-09-29 16:53 UTC, nguyenluc99 commented on python/common/org/python/stdlib/datetime/Date.java
> +        return new org.python.types.Str(weekdayStr + " " + monthStr + " " + dayStr + " 00:00:00 " + yearStr);
If the year is less than 10, for example yearNum=5, the previous code will print like ...00:00:00 5, but python3 print it like ...00:00:00 0005, so we need to add extra "000" before printing the year. If it is not less than 10, it should be check for being less than 100, to add only "00" in front of it. Similar to the case of being less than 1000.

2020-09-30 08:30 UTC, nguyenluc99 approved these changes
so nice

2020-09-30 20:14 UTC, DavidOstlund approved these changes

2020-09-30 20:24 UTC, ponterik approved these changes

2020-10-01 05:21 UTC, merged